added footer, adjusted to mobile version,
Adrianm7777/store-page pull request #6
Opened 2023-12-05 10:47 UTC by Adrianm7777

2023-12-05 19:11 UTC, Materka11 requested changes

2023-12-05 19:11 UTC, Materka11 commented on src/MainPage/Components/Footer/Footer.module.scss
> +}
Zrob z tego jedna klase

2023-12-05 19:11 UTC, Materka11 commented on src/MainPage/Components/Footer/Footer.tsx
> +        ))}
Tutaj mozesz uzyc destrukturyzacji obiektu w paramsach

2023-12-05 19:11 UTC, Materka11 commented on src/MainPage/Components/Footer/Footer.tsx
> +        ))}
Tutaj jest ten sam case co wyzej

2023-12-06 10:40 UTC, Adrianm7777 commented on src/MainPage/Components/Footer/Footer.module.scss
> +}
Nie mogę. Używam ich w ustawieniach na mobilna wersje

2023-12-06 16:40 UTC, Materka11 approved these changes

2023-12-06 16:40 UTC, merged